# ========================================
#         InfernalTreasures Config
# ========================================
# Configuration for treasure hunting while mining

# ========================================
#           TREASURE SETTINGS
# ========================================
treasure:
  # Base chance of finding a treasure when mining (0-100%)
  spawn-chance: 15
  
  # Play sound and particle effects when treasures are found
  effects:
    sound: true
    particles: true
    
  # Announce treasure finds to the server (per rarity)
  announce-finds:
    common: false      # Don't announce common treasures
    rare: false        # Don't announce rare treasures
    epic: false        # Don't announce epic treasures
    legendary: true    # Announce legendary treasures
    mythic: true       # Announce mythic treasures
  
  # Maximum treasures a player can find per hour (0 = unlimited)
  hourly-limit: 50

# ========================================
#          HOLOGRAM SETTINGS
# ========================================
holograms:
  # Enable or disable holograms for specific treasure rarities
  # Set to true to show hologram, false to hide it
  enabled-rarities:
    common: false     # No hologram for common treasures
    rare: false       # No hologram for rare treasures  
    epic: false       # No hologram for epic treasures
    legendary: true   # Show hologram for legendary treasures
    mythic: true      # Show hologram for mythic treasures
  
  # Global hologram settings
  height: 1.5         # Height above barrel (in blocks)
  visible-distance: 16 # Distance players can see holograms (in blocks)

# ========================================
#           MINING SETTINGS
# ========================================
mining:
  # Blocks that can drop treasures when mined
  enabled-blocks:
    # Stone variants
    - STONE
    - DEEPSLATE
    - GRANITE
    - DIORITE
    - ANDESITE
    - TUFF
    - CALCITE
    
    # Overworld ores
    - COAL_ORE
    - IRON_ORE
    - COPPER_ORE
    - GOLD_ORE
    - REDSTONE_ORE
    - LAPIS_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    
    # Deepslate ores
    - DEEPSLATE_COAL_ORE
    - DEEPSLATE_IRON_ORE
    - DEEPSLATE_COPPER_ORE
    - DEEPSLATE_GOLD_ORE
    - DEEPSLATE_REDSTONE_ORE
    - DEEPSLATE_LAPIS_ORE
    - DEEPSLATE_DIAMOND_ORE
    - DEEPSLATE_EMERALD_ORE
    
    # Nether blocks
    - NETHER_GOLD_ORE
    - NETHER_QUARTZ_ORE
    - NETHERRACK
    - BLACKSTONE
    - BASALT
    
    # End blocks
    - END_STONE
  
  # Only allow treasure drops when using pickaxes
  require-pickaxe: true
  
  # Y level range for treasure spawns
  min-y-level: -64
  max-y-level: 320

# ========================================
#           RARITY SETTINGS
# ========================================
rarity:
  # Percentage chance for each rarity tier (should add up to 100%)
  chances:
    COMMON: 60
    RARE: 25
    EPIC: 10
    LEGENDARY: 4
    MYTHIC: 1
  
  # Color codes for rarity display
  colors:
    COMMON: "&f"      # White
    RARE: "&9"        # Blue
    EPIC: "&5"        # Purple
    LEGENDARY: "&6"   # Gold
    MYTHIC: "&c"      # Red

# ========================================
#          BIOME SETTINGS
# ========================================
biomes:
  # Enable biome-specific loot tables
  enabled: true
  
  # Use default loot when biome config is missing
  use-default-loot: true
  
  # Biome-specific configurations are located in the 'biomes/' folder
  # Available biomes: desert.yml, forest.yml, ocean.yml, plains.yml
  # Each biome has its own loot table with different treasure types
  
  # Biome detection settings
  detection:
    # Check biome at player location or block location
    use-player-location: true
    
    # Cache biome lookups for performance (recommended: true)
    cache-biome-lookups: true

# ========================================
#          PLAYER SETTINGS
# ========================================
player:
  # Send messages to players when they find treasures
  notifications: true
  
  # Show treasure statistics
  show-stats: true
  
  # Save player statistics
  save-stats: true

# ========================================
#           DEBUG SETTINGS
# ========================================
debug:
  # Enable debug logging for troubleshooting
  enabled: true
  
  # Specific debug categories (only work if debug.enabled is true)
  categories:
    loot-generation: true     # Debug loot generation process
    treasure-spawning: true   # Debug treasure spawning
    mmo-items: true          # Debug MMOItems integration
    executable-items: true   # Debug ExecutableItems integration
    barrel-filling: true     # Debug barrel inventory filling
    biome-detection: true    # Debug biome detection