# ========================================
#         InfernalTreasures Config
# ========================================
# Configuration for treasure hunting while mining

# ========================================
#           WORLD SETTINGS
# ========================================
worlds:
  # World whitelist - treasures will only spawn in these worlds
  # Leave empty to allow treasures in all worlds
  # World names are case-sensitive and must match exactly
  whitelist:
    - "world"
    - "world_nether"
    - "world_the_end"
  
  # Whether to use the whitelist (true) or blacklist (false)
  # true = Only allow treasures in whitelisted worlds
  # false = Allow treasures in all worlds EXCEPT blacklisted worlds
  use-whitelist: true
  
  # World blacklist - treasures will NOT spawn in these worlds (only used if use-whitelist is false)
  blacklist:
    - "creative_world"
    - "spawn_world"

# ========================================
#           TREASURE SETTINGS
# ========================================
treasure:
  # Global effects toggle (master switch)
  effects:
    sound: true
    particles: true
    
  # Barrel despawn behavior
  despawn:
    # Whether items should drop when barrel despawns (this might cause lag if many items are dropped)
    drop-items-on-despawn: false
  
  # Difficulty system - affects required_blocks_mined values
  difficulty:
    # Current difficulty setting: EASY, MEDIUM, HARD, EXTREME
    current: "EASY"
    
    # Multipliers for required_blocks_mined values
    multipliers:
      easy: 1.0      # No change (x1)
      medium: 2.0    # Double requirements (x2)
      hard: 3.0      # Triple requirements (x3)
      extreme: 4.0   # Quadruple requirements (x4)
    
    # Whether to affect range-type requirements like "0-99999"
    # If true: "0-99999" becomes "0-399996" on extreme difficulty
    # If false: range-type requirements are not affected by difficulty
    affect-range-requirements: true
    
  # Loot progression system
  # Controls how many slots in the barrel are filled (barrel has 27 slots total)
  loot-progression:
    # Current progression level (1-4)
    current-level: 1
    
    # Slot configuration for each level
    levels:
      1:
        slots: 7     # Level 1: Only 7 slots are filled
        name: "Beginner"
        description: "Basic treasure progression"
      2:
        slots: 14    # Level 2: 14 slots are filled
        name: "Intermediate" 
        description: "Improved treasure progression"
      3:
        slots: 21    # Level 3: 21 slots are filled
        name: "Advanced"
        description: "Enhanced treasure progression"
      4:
        slots: 27    # Level 4: All 27 slots are filled (fastest progression)
        name: "Master"
        description: "Maximum treasure progression"
    
    # Loot generation mode
    # true = Use chance-based system (items may miss their chance and slots may be empty)
    # false = Guarantee all slots are filled (ignore individual item chances)
    use-chance-based-system: false
    
    # Shulker Box loot generation settings
    shulker-box-loot:
      # Whether to apply the same progression system to Shulker Box contents
      # true = Use the same progression slots for Shulker Box contents
      # false = Use fixed slot count specified below
      use-progression-system: true
      
      # Fixed number of slots to fill in Shulker Boxes (only used if use-progression-system is false)
      # Shulker Boxes have 27 slots total
      fixed-slots: 9
      
      # Whether to use chance-based system for Shulker Box contents
      # true = Apply individual item chances inside Shulker Boxes
      # false = Guarantee all selected slots are filled (ignore individual item chances)
      use-chance-based-system: false
    
    # Enable debug logging for progression system
    debug: true

  # Per-rarity sound and particle effects
  rarity-effects:
    common:
      enabled: true
      sound:
        type: ENTITY_EXPERIENCE_ORB_PICKUP
        volume: 0.8
        pitch: 1.0
      particles:
        type: VILLAGER_HAPPY
        count: 15
        offset: 0.5
    
    rare:
      enabled: true
      sound:
        type: ENTITY_PLAYER_LEVELUP
        volume: 1.0
        pitch: 1.2
      particles:
        type: ENCHANTMENT_TABLE
        count: 25
        offset: 0.8
    
    epic:
      enabled: true
      sound:
        type: ENTITY_ENDER_EYE_LAUNCH
        volume: 1.2
        pitch: 0.8
      particles:
        type: PORTAL
        count: 35
        offset: 1.0
    
    legendary:
      enabled: true
      sound:
        type: ENTITY_WITHER_SPAWN
        volume: 1.5
        pitch: 1.5
      particles:
        type: DRAGON_BREATH
        count: 50
        offset: 1.2
    
    mythic:
      enabled: true
      sound:
        type: ENTITY_ENDER_DRAGON_DEATH
        volume: 2.0
        pitch: 0.5
      particles:
        type: END_ROD
        count: 75
        offset: 1.5
    
  # Announce treasure finds to the server (per rarity)
  announce-finds:
    common: false      
    rare: false        
    epic: false        
    legendary: true    
    mythic: true      
  
  # Maximum treasures a player can find per hour (0 = unlimited)
  hourly-limit: 0

# ========================================
#          HOLOGRAM SETTINGS
# ========================================
holograms:
  # Enable or disable holograms for specific treasure rarities
  # Set to true to show hologram, false to hide it
  enabled-rarities:
    common: false     
    rare: false       
    epic: false       
    legendary: true   
    mythic: true      
  
  # Global hologram settings
  height: 1.5         # Height above barrel (in blocks)
  visible-distance: 16 # Distance players can see holograms (in blocks)

# ========================================
#           MINING SETTINGS
# ========================================
mining:
  # Only allow treasure drops when using pickaxes
  require-pickaxe: true
  
  # Y level range for treasure spawns
  min-y-level: -64
  max-y-level: 320

# ========================================
#          BIOME SETTINGS
# ========================================
biomes:
  # Enable biome-specific loot tables
  enabled: true
  
  # Use default loot when biome config is missing
  use-default-loot: true
  
  # Biome-specific configurations are located in the 'biomes/' folder
  # Available biomes: desert.yml, forest.yml, ocean.yml, plains.yml
  # Each biome has its own loot table with different treasure types
  
  # Biome detection settings
  detection:
    # Check biome at player location or block location
    use-player-location: true
    
    # Cache biome lookups for performance (recommended: true)
    cache-biome-lookups: true

# ========================================
#          PLAYER SETTINGS
# ========================================
player:
  # Send messages to players when they find treasures
  notifications: true
  
  # Show treasure statistics
  show-stats: true
  
  # Save player statistics
  save-stats: true

# ========================================
#         DATABASE SETTINGS
# ========================================
database:
  # Storage type: YML, SQLITE, or MYSQL
  type: "YML"
  
  # SQLite settings (only used if type is SQLITE)
  sqlite:
    # Database file name (will be created in plugin folder)
    filename: "stats.db"
    
  # MySQL settings (only used if type is MYSQL)
  mysql:
    host: "localhost"
    port: 3306
    database: "infernal_treasures"
    username: "root"
    password: "password"
    # Connection pool settings
    pool:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    # SSL settings
    ssl:
      enabled: false
      trust-certificate: false
    # Additional connection properties
    properties:
      useSSL: false
      allowPublicKeyRetrieval: true
      serverTimezone: "UTC"

# ========================================
#          RARITY SETTINGS
# ========================================
rarity:
  # How long each rarity of treasure stays before despawning (in seconds)
  despawn-times:
    common: 300       # 5 minutes
    rare: 420         # 7 minutes  
    epic: 600         # 10 minutes
    legendary: 900    # 15 minutes
    mythic: 1200      # 20 minutes

# ========================================
#           DEBUG SETTINGS
# ========================================
debug:
  enabled: true
  categories:
    loot-generation: true
    treasure-spawning: true
    mmo-items: true
    executable-items: true
    executable-blocks: true
    barrel-filling: true
    biome-detection: true
    progression-debug: true