# ========================================
#         InfernalTreasures Config
# ========================================
# Configuration for treasure hunting while mining

# ========================================
#           TREASURE SETTINGS
# ========================================
treasure:
  # Global effects toggle (master switch)
  effects:
    sound: true
    particles: true
    
  # Per-rarity sound and particle effects
  rarity-effects:
    common:
      enabled: true
      sound:
        type: ENTITY_EXPERIENCE_ORB_PICKUP
        volume: 0.8
        pitch: 1.0
      particles:
        type: VILLAGER_HAPPY
        count: 15
        offset: 0.5
    
    rare:
      enabled: true
      sound:
        type: ENTITY_PLAYER_LEVELUP
        volume: 1.0
        pitch: 1.2
      particles:
        type: ENCHANTMENT_TABLE
        count: 25
        offset: 0.8
    
    epic:
      enabled: true
      sound:
        type: ENTITY_ENDER_EYE_LAUNCH
        volume: 1.2
        pitch: 0.8
      particles:
        type: PORTAL
        count: 35
        offset: 1.0
    
    legendary:
      enabled: true
      sound:
        type: ENTITY_WITHER_SPAWN
        volume: 1.5
        pitch: 1.5
      particles:
        type: DRAGON_BREATH
        count: 50
        offset: 1.2
    
    mythic:
      enabled: true
      sound:
        type: ENTITY_ENDER_DRAGON_DEATH
        volume: 2.0
        pitch: 0.5
      particles:
        type: END_ROD
        count: 75
        offset: 1.5
    
  # Announce treasure finds to the server (per rarity)
  announce-finds:
    common: false      
    rare: false        
    epic: false        
    legendary: true    
    mythic: true      
  
  # Maximum treasures a player can find per hour (0 = unlimited)
  hourly-limit: 0

# ========================================
#          HOLOGRAM SETTINGS
# ========================================
holograms:
  # Enable or disable holograms for specific treasure rarities
  # Set to true to show hologram, false to hide it
  enabled-rarities:
    common: false     
    rare: false       
    epic: false       
    legendary: true   
    mythic: true      
  
  # Global hologram settings
  height: 1.5         # Height above barrel (in blocks)
  visible-distance: 16 # Distance players can see holograms (in blocks)

# ========================================
#           MINING SETTINGS
# ========================================
mining:
  # Only allow treasure drops when using pickaxes
  require-pickaxe: true
  
  # Y level range for treasure spawns
  min-y-level: -64
  max-y-level: 320

# ========================================
#          BIOME SETTINGS
# ========================================
biomes:
  # Enable biome-specific loot tables
  enabled: true
  
  # Use default loot when biome config is missing
  use-default-loot: true
  
  # Biome-specific configurations are located in the 'biomes/' folder
  # Available biomes: desert.yml, forest.yml, ocean.yml, plains.yml
  # Each biome has its own loot table with different treasure types
  
  # Biome detection settings
  detection:
    # Check biome at player location or block location
    use-player-location: true
    
    # Cache biome lookups for performance (recommended: true)
    cache-biome-lookups: true

# ========================================
#          PLAYER SETTINGS
# ========================================
player:
  # Send messages to players when they find treasures
  notifications: true
  
  # Show treasure statistics
  show-stats: true
  
  # Save player statistics
  save-stats: true

# ========================================
#          RARITY SETTINGS
# ========================================
rarity:
  # How long each rarity of treasure stays before despawning (in seconds)
  despawn-times:
    common: 300       # 5 minutes
    rare: 420         # 7 minutes  
    epic: 600         # 10 minutes
    legendary: 900    # 15 minutes
    mythic: 1200      # 20 minutes

# ========================================
#           DEBUG SETTINGS
# ========================================
debug:
  enabled: false
  categories:
    loot-generation: true
    treasure-spawning: true
    mmo-items: true
    executable-items: true
    barrel-filling: true
    biome-detection: true