# ========================================
#         InfernalTreasures Config
# ========================================
# Configuration for treasure hunting while mining

# ========================================
#           TREASURE SETTINGS
# ========================================
treasure:
  # Base chance of finding a treasure when mining (0-100%)
  spawn-chance: 15
  
  # Play sound and particle effects when treasures are found
  effects:
    sound: true
    particles: true
    
  # Announce rare treasure finds to the server (RARE and above)
  announce-finds: true
  
  # Maximum treasures a player can find per hour (0 = unlimited)
  hourly-limit: 50

# ========================================
#           MINING SETTINGS
# ========================================
mining:
  # Blocks that can drop treasures when mined
  enabled-blocks:
    # Stone variants
    - STONE
    - DEEPSLATE
    - GRANITE
    - DIORITE
    - ANDESITE
    - TUFF
    - CALCITE
    
    # Overworld ores
    - COAL_ORE
    - IRON_ORE
    - COPPER_ORE
    - GOLD_ORE
    - REDSTONE_ORE
    - LAPIS_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    
    # Deepslate ores
    - DEEPSLATE_COAL_ORE
    - DEEPSLATE_IRON_ORE
    - DEEPSLATE_COPPER_ORE
    - DEEPSLATE_GOLD_ORE
    - DEEPSLATE_REDSTONE_ORE
    - DEEPSLATE_LAPIS_ORE
    - DEEPSLATE_DIAMOND_ORE
    - DEEPSLATE_EMERALD_ORE
    
    # Nether blocks
    - NETHER_GOLD_ORE
    - NETHER_QUARTZ_ORE
    - NETHERRACK
    - BLACKSTONE
    - BASALT
    
    # End blocks
    - END_STONE
  
  # Only allow treasure drops when using pickaxes
  require-pickaxe: true
  
  # Y level range for treasure spawns
  min-y-level: -64
  max-y-level: 320

# ========================================
#           RARITY SETTINGS
# ========================================
rarity:
  # Percentage chance for each rarity tier (should add up to 100%)
  chances:
    COMMON: 60
    RARE: 25
    EPIC: 10
    LEGENDARY: 4
    MYTHIC: 1
  
  # Color codes for rarity display
  colors:
    COMMON: "&f"      # White
    RARE: "&9"        # Blue
    EPIC: "&5"        # Purple
    LEGENDARY: "&6"   # Gold
    MYTHIC: "&c"      # Red

# ========================================
#          BIOME SETTINGS
# ========================================
biomes:
  # Enable biome-specific loot tables
  enabled: true
  
  # Use default loot when biome config is missing
  use-default-loot: true
  
  # Biome-specific configurations are located in the 'biomes/' folder
  # Available biomes: desert.yml, forest.yml, ocean.yml, plains.yml
  # Each biome has its own loot table with different treasure types
  
  # Biome detection settings
  detection:
    # Check biome at player location or block location
    use-player-location: true
    
    # Cache biome lookups for performance (recommended: true)
    cache-biome-lookups: true

# ========================================
#          PLAYER SETTINGS
# ========================================
player:
  # Send messages to players when they find treasures
  notifications: true
  
  # Show treasure statistics
  show-stats: true
  
  # Save player statistics
  save-stats: true

# ========================================
#            MESSAGES
# ========================================
messages:
  treasure-found: "&6✦ &e{player} &7found a &{rarity_color}{rarity} &7treasure in {biome}!"
  personal-find: "&6✦ &7You found a &{rarity_color}{rarity} &7treasure!"
  no-permission: "&cYou don't have permission to use this command!"
  config-reloaded: "&aConfiguration reloaded successfully!"
  biomes-loaded: "&aBiome configurations loaded: {count} biomes"
  biome-not-found: "&cBiome configuration not found for {biome}, using default loot"