name: InfernalTresures
version: '1.0'
main: me.itzrenzo.infernaltresures.InfernalTresures
api-version: '1.21'
load: STARTUP
authors: [ ItzRenzo ]
description: A plugin that spawns treasures with different rarities when mining blocks
softdepend: [SCore, MMOItems, ExecutableItems, ExecutableBlocks]

commands:
  treasure:
    description: Main command for the InfernalTreasures plugin
    usage: /<command> [spawn|reload|info|stats|loot|help]
    permission: infernaltresures.command.use
    aliases: [treasures, tr]
  lootgui:
    description: Opens the loot GUI to browse biome treasures
    usage: /<command>
    permission: infernaltresures.command.loot.gui
    aliases: [tloot, treasureloot]
    
permissions:
  infernaltresures.command.use:
    description: Allows using the basic treasure command
    default: true
  infernaltresures.command.spawn:
    description: Allows spawning treasures manually
    default: op
  infernaltresures.command.reload:
    description: Allows reloading the plugin configuration
    default: op
  infernaltresures.command.info:
    description: Allows viewing plugin information
    default: op
  infernaltresures.command.stats:
    description: Allows viewing your own treasure hunting statistics
    default: true
  infernaltresures.command.stats.others:
    description: Allows viewing other players' treasure hunting statistics
    default: op
  infernaltresures.command.stats.set:
    description: Allows setting player statistics
    default: op
  infernaltresures.command.loot:
    description: Allows using the loot command
    default: true
  infernaltresures.command.loot.gui:
    description: Allows opening the loot GUI to browse biome treasures
    default: true
  infernaltresures.command.luck:
    description: Allows giving treasure luck to players
    default: op
  infernaltresures.command.toggle:
    description: Allows toggling treasure spawning on/off for yourself
    default: true
  infernaltresures.command.progression:
    description: Allows managing loot progression settings
    default: op
